export const FETCH_CHORD_MAP = 'FETCH_CHORD_MAP';
export const ADD_CHORD_TO_DOCK = 'ADD_CHORD_TO_DOCK';
export const REMOVE_CHORD_FROM_DOCK = 'REMOVE_CHORD_FROM_DOCK';
export const REORDER_DOCK = 'REORDER_DOCK';
export const UPDATE_PARAMETER = 'UPDATE_PARAMETER';
export const PREVIEW_CHORD = 'PREVIEW_CHORD';
